// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxzDARu1x25Yix1aVuBYcpjyidg4fp3Q',
    appId: '1:688435936708:web:46172d5a2d44468bd03891',
    messagingSenderId: '688435936708',
    projectId: 'barza-mobile-app',
    authDomain: 'barza-mobile-app.firebaseapp.com',
    storageBucket: 'barza-mobile-app.firebasestorage.app',
    measurementId: 'G-CVZYZEY745',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALq4o9R-4qUhr3OKlME7sAXTYA8NLlahY',
    appId: '1:688435936708:android:261ff7da15ec7e1dd03891',
    messagingSenderId: '688435936708',
    projectId: 'barza-mobile-app',
    storageBucket: 'barza-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsoT9nk_BhxrisZ8rF2F1rz9uzfDOvr2M',
    appId: '1:688435936708:ios:1452aff9b114146bd03891',
    messagingSenderId: '688435936708',
    projectId: 'barza-mobile-app',
    storageBucket: 'barza-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.barzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsoT9nk_BhxrisZ8rF2F1rz9uzfDOvr2M',
    appId: '1:688435936708:ios:1452aff9b114146bd03891',
    messagingSenderId: '688435936708',
    projectId: 'barza-mobile-app',
    storageBucket: 'barza-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.barzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxzDARu1x25Yix1aVuBYcpjyidg4fp3Q',
    appId: '1:688435936708:web:8296cfaddd2a1d49d03891',
    messagingSenderId: '688435936708',
    projectId: 'barza-mobile-app',
    authDomain: 'barza-mobile-app.firebaseapp.com',
    storageBucket: 'barza-mobile-app.firebasestorage.app',
    measurementId: 'G-8KBGRRQWTR',
  );
}
